version: "3.5"
services:
  usermanagement:
    build:
      context: user-management
    ports:
      - 3001:3001
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/users