version: "3.5"
services:

  # ####################################################################################################################
  # Mongo DB instance
  # ####################################################################################################################
  mongo:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - /data/users
    networks:
      - mongo_net

  # ####################################################################################################################
  # Recommender service
  # ####################################################################################################################
  recommender:
    build:
      context: recommender
    container_name: "recommender"
    env_file:
      - ./creds.env
    networks:
      - neo4j_net
    ports:
      - 3000:3000

    ####################################################################################################################
    # Neo4j
    # ####################################################################################################################
  neo4j:
    container_name: "neo4jdb"
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/dbms:/data/dbms
    networks:
      - neo4j_net

   ####################################################################################################################
   #User Management service
   ####################################################################################################################
  usermanagement:
    build:
      context: user-management
    container_name: "users"
    restart: always
    ports:
      - 3001:3001
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo_net

networks:
  mongo_net:
  neo4j_net: