version: "3.5"
services:

  # ####################################################################################################################
  # Mongo DB instance
  # ####################################################################################################################
  mongo:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - /data/users

  # ####################################################################################################################
  # Recommender service
  # ####################################################################################################################
  recommender:
    build:
      context: recommender
    container_name: "recommender"
    ports:
      - 3000:3000

    ####################################################################################################################
    # Neo4j
    # ####################################################################################################################
    neo4j:
      image: latest
      ports:
        - "17474:7474"
      volumes:
        - ./db/dbms:/data/dbms

  # ####################################################################################################################
  # User Management service
  # ####################################################################################################################
#  usermanagement:
#    build:
#      context: user-management
#    container_name: "users"
#    ports:
#      - 3001:3001
#    depends_on:
#      - mongo